import { GistDesignFile, BeforeAfterItem } from '@/types/file';
import { generateGistDesignMarkdown } from './markdown';

export function generateDeveloperBrief(
  file: GistDesignFile,
  beforeAfter: BeforeAfterItem[]
): string {
  const productName = file.product.name || 'your product';
  let brief = '';

  // Header
  brief += `# Developer Brief: ${productName}\n\n`;
  brief += `This brief was generated by gist.design to help AI coding tools understand your design decisions.\n\n`;

  // Setup Instructions
  brief += `## Setup Instructions\n\n`;
  brief += `1. Save the \`.gist.design\` file to the root of your project\n`;
  brief += `2. Reference it in your \`llms.txt\` file (see snippet below)\n`;
  brief += `3. When using AI tools, point them to the gist.design file for context\n\n`;

  // llms.txt snippet
  brief += `## llms.txt Snippet\n\n`;
  brief += '```\n';
  brief += `# Design Decisions\n`;
  brief += `> This project uses a gist.design file for design decisions.\n`;
  brief += `> Read .gist.design before implementing any UI changes.\n`;
  brief += `> It contains intent, interaction models, and explicit design decisions.\n`;
  brief += '```\n\n';

  // Verify It Works
  brief += `## Verify It Works\n\n`;
  brief += `After setting up, test with these prompts:\n\n`;
  const features = file.features.map((f) => f.name).join(', ');
  brief += `- "What design patterns does ${productName} use for ${file.features[0]?.name || 'its main feature'}?"\n`;
  brief += `- "I need to add error handling to ${file.features[0]?.name || 'a feature'}. What does the gist.design file say?"\n`;
  brief += `- "What did we explicitly decide NOT to do?"\n\n`;
  brief += `If the tool references your gist.design decisions in its response, it's working.\n\n`;

  // Before/After section
  if (beforeAfter.length > 0) {
    brief += `## What This File Fixes\n\n`;
    brief += `| Without gist.design | With gist.design |\n`;
    brief += `|---------------------|-------------------|\n`;
    beforeAfter.forEach((item) => {
      brief += `| ${item.without} | ${item.with} |\n`;
    });
    brief += '\n';
  }

  // AI Tool Integration Guides
  brief += `## AI Tool Integration\n\n`;

  brief += `### Cursor\n`;
  brief += `Add to your \`.cursorrules\` file:\n`;
  brief += '```\n';
  brief += `Read .gist.design before implementing UI changes. It contains design decisions, interaction patterns, and explicit "not this" guidance.\n`;
  brief += '```\n\n';

  brief += `### Claude Code\n`;
  brief += `Add to your \`CLAUDE.md\` file:\n`;
  brief += '```\n';
  brief += `When working on UI: read .gist.design first. It defines design intent, interaction models, and design decisions for each feature.\n`;
  brief += '```\n\n';

  brief += `### ChatGPT\n`;
  brief += `Upload the .gist.design file as context, then prompt:\n`;
  brief += '```\n';
  brief += `I've attached our design decisions file. Use it as context when suggesting UI implementations.\n`;
  brief += '```\n\n';

  brief += `### Claude\n`;
  brief += `Add the .gist.design file to your project knowledge, then:\n`;
  brief += '```\n';
  brief += `Reference the gist.design file for design decisions before suggesting any UI changes.\n`;
  brief += '```\n\n';

  brief += `### Copilot\n`;
  brief += `Reference in your workspace:\n`;
  brief += '```\n';
  brief += `@workspace Read .gist.design for design context before implementing this feature.\n`;
  brief += '```\n\n';

  // Full file content
  brief += `## Full gist.design File\n\n`;
  brief += '```markdown\n';
  brief += generateGistDesignMarkdown(file);
  brief += '```\n';

  return brief;
}
