import { GistDesignFile, BeforeAfterItem } from '@/types/file';
import { generateGistDesignMarkdown } from './markdown';

export function generateDeveloperBrief(
  file: GistDesignFile,
  beforeAfter: BeforeAfterItem[]
): string {
  const productName = file.product.name || 'your product';
  let brief = '';

  // Header
  brief += `# Developer Brief: ${productName}\n\n`;
  brief += `This brief was generated by gist to help AI tools understand your product context.\n\n`;

  // Setup Instructions
  brief += `## Setup Instructions\n\n`;
  brief += `1. Save the file as \`llms.gist\` at the root of your project (mirrors \`llms.txt\`)\n`;
  brief += `2. Reference it in your \`llms.txt\` file (see snippet below)\n`;
  brief += `3. When using AI tools, point them to the llms.gist file for context\n\n`;

  // llms.txt snippet
  brief += `## llms.txt Snippet\n\n`;
  brief += '```\n';
  brief += `# Product context for AI\n`;
  brief += `> This project uses a llms.gist file describing what the product is, who it's for, and what AI tools commonly get wrong.\n`;
  brief += `> Read .gist before answering questions about this product.\n`;
  brief += '```\n\n';

  // Verify It Works
  brief += `## Verify It Works\n\n`;
  brief += `After setting up, test with these prompts:\n\n`;
  brief += `- "What is ${productName}?"\n`;
  brief += `- "Who is ${productName} for, and who is it not for?"\n`;
  brief += `- "What does ${productName} explicitly NOT do?"\n\n`;
  brief += `If the tool references the contents of your llms.gist file in its response, it's working.\n\n`;

  // Before/After section
  if (beforeAfter.length > 0) {
    brief += `## What This File Fixes\n\n`;
    brief += `| Without .gist | With .gist |\n`;
    brief += `|---------------|------------|\n`;
    beforeAfter.forEach((item) => {
      brief += `| ${item.without} | ${item.with} |\n`;
    });
    brief += '\n';
  }

  // AI Tool Integration Guides
  brief += `## AI Tool Integration\n\n`;

  brief += `### Cursor\n`;
  brief += `Add to your \`.cursorrules\` file:\n`;
  brief += '```\n';
  brief += `Read .gist before answering questions about this product. It contains positioning, audience, and explicit "not this" guidance.\n`;
  brief += '```\n\n';

  brief += `### Claude Code\n`;
  brief += `Add to your \`CLAUDE.md\` file:\n`;
  brief += '```\n';
  brief += `Read .gist first when discussing this product. It defines what the product is, who it's for, and corrections to common AI misunderstandings.\n`;
  brief += '```\n\n';

  brief += `### ChatGPT\n`;
  brief += `Upload the llms.gist file as context, then prompt:\n`;
  brief += '```\n';
  brief += `I've attached our product context. Use it as ground truth when answering questions about ${productName}.\n`;
  brief += '```\n\n';

  brief += `### Claude\n`;
  brief += `Add the llms.gist file to your project knowledge, then:\n`;
  brief += '```\n';
  brief += `Reference the llms.gist file before answering anything about this product.\n`;
  brief += '```\n\n';

  brief += `### Copilot\n`;
  brief += `Reference in your workspace:\n`;
  brief += '```\n';
  brief += `@workspace Read .gist for product context before answering.\n`;
  brief += '```\n\n';

  // Full file content
  brief += `## Full .gist File\n\n`;
  brief += '```markdown\n';
  brief += generateGistDesignMarkdown(file);
  brief += '```\n';

  return brief;
}
